//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerChartered.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Satisfactions = new HashSet<Satisfaction>();
        }
    
        public int CustomerId { get; set; }
        public string ParentId { get; set; }
        public string ChildId { get; set; }
        public string DepartmentId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string ServiceId { get; set; }
        public string ServiceDetailId { get; set; }
        public string TimeframeId { get; set; }
        public string TinNumber { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string MinuteTook { get; set; }
        public string Evaluate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satisfaction> Satisfactions { get; set; }
    }
}
