//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerChartered.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceDetail()
        {
            this.Timeframes = new HashSet<Timeframe>();
        }
    
        public string ServiceDetailId { get; set; }
        public string ServiceDetailName { get; set; }
        public string ServiceId { get; set; }
    
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timeframe> Timeframes { get; set; }
    }
}
